[package]
name = "dugong-indexer"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
name = "dugong_indexer"
path = "src/lib.rs"

[[bin]]
name = "dugong-indexer"
path = "src/main.rs"

[dependencies]
dugong-core.workspace = true

tokio.workspace = true
async-trait.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
sqlx.workspace = true
chrono.workspace = true
dotenvy.workspace = true

[dev-dependencies]
wiremock.workspace = true
tokio = { workspace = true }
