#!/usr/bin/env -S npx --yes tsx
// Create a treasury DugongAccount on Sui by calling
// `dugong::account::init_account_no_signature(registry, xid, handle)` and
// record the resulting shared object ID in contracts/move/dugong/Treasury.toml
// keyed by network. deploy-contract.ts reads that file as a fallback when
// --treasury-account isn't passed, so once created the ID survives re-deploys.
//
// Defaults (when flags are omitted):
//   --package-id   ← DUGONG_PACKAGE_ID  from apps/api/.env
//   --registry-id  ← DUGONG_REGISTRY_ID from apps/api/.env
//
// Usage:
//   scripts/create-treasury.ts [flags]
//
// Flags:
//   --network testnet|mainnet    Sui network (default: testnet).
//   --package-id <id>            Override DUGONG_PACKAGE_ID source.
//   --registry-id <id>           Override DUGONG_REGISTRY_ID source.
//   --xid <str>                  Treasury xid (default: TREASURY). Must be
//                                unique across the registry on this network.
//   --handle <str>               Display handle (default: treasury).
//   --gas-budget <MIST>          Gas budget (default: 100000000).
//   --force                      Overwrite an existing entry for this network.
//   --dry-run                    Print the sui command without executing.
//   --help                       Show this message.

import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dugongDir = resolve(repoRoot, "contracts/move/dugong");
const treasuryToml = resolve(dugongDir, "Treasury.toml");
const apiEnv = resolve(repoRoot, "apps/api/.env");

// ── helpers ──────────────────────────────────────────────────────────────────

function die(msg: string): never {
  process.stderr.write(`error: ${msg}\n`);
  process.exit(1);
}

function info(msg: string): void {
  process.stderr.write(`info   ${msg}\n`);
}

function run(
  cmd: string,
  args: string[],
  opts: { dryRun?: boolean; cwd?: string; captureStdout?: boolean } = {}
): string {
  const pretty = [cmd, ...args].join(" ");
  if (opts.dryRun) {
    process.stdout.write(`[dry-run] ${pretty}\n`);
    return "";
  }
  info(`$ ${pretty}`);
  const result = spawnSync(cmd, args, {
    cwd: opts.cwd ?? repoRoot,
    stdio: opts.captureStdout ? ["inherit", "pipe", "inherit"] : "inherit",
    encoding: "utf8",
  });
  if (result.error) die(`spawn failed: ${result.error.message}`);
  if (result.status !== 0) die(`command exited with status ${result.status}`);
  return (result.stdout as string | null) ?? "";
}

/** Read a single KEY=value line from a .env file. Returns null if missing. */
function readEnvKey(envFile: string, key: string): string | null {
  if (!existsSync(envFile)) return null;
  const raw = readFileSync(envFile, "utf8");
  const re = new RegExp(`^${key}=(.*)$`, "m");
  const m = re.exec(raw);
  return m?.[1]?.trim() || null;
}

function patchEnvKey(envFile: string, key: string, value: string): void {
  const raw = existsSync(envFile) ? readFileSync(envFile, "utf8") : "";
  const line = `${key}=${value}`;
  const re = new RegExp(`^${key}=.*$`, "m");
  const next = re.test(raw)
    ? raw.replace(re, line)
    : raw.trimEnd() + (raw.length ? "\n" : "") + line + "\n";
  writeFileSync(envFile, next.endsWith("\n") ? next : next + "\n", "utf8");
  info(`Patched ${apiEnv}: ${key}`);
}

/** Encode a UTF-8 string as the JSON byte-array literal Sui CLI expects. */
function encodeVecU8(s: string): string {
  return `[${[...Buffer.from(s, "utf8")].join(",")}]`;
}

// ── Treasury.toml ─────────────────────────────────────────────────────────────

type TreasuryEntry = {
  accountId: string;
  xid: string;
  handle: string;
  createdAt: string;
};

function readTreasuryToml(network: string): TreasuryEntry | null {
  if (!existsSync(treasuryToml)) return null;
  const raw = readFileSync(treasuryToml, "utf8");
  const sectionRe = new RegExp(`\\[treasury\\.${network}\\]([^\\[]*)`);
  const m = sectionRe.exec(raw);
  if (!m) return null;
  const section = m[1]!;
  const get = (key: string) => {
    const re = new RegExp(`^${key}\\s*=\\s*"([^"]+)"`, "m");
    return re.exec(section)?.[1] ?? null;
  };
  const accountId = get("account-id");
  if (!accountId) return null;
  return {
    accountId,
    xid: get("xid") ?? "",
    handle: get("handle") ?? "",
    createdAt: get("created-at") ?? "",
  };
}

function writeTreasuryToml(network: string, entry: TreasuryEntry): void {
  const header =
    "# Generated by scripts/create-treasury.ts\n" +
    "# This file records the treasury DugongAccount object ID per network.\n" +
    "# It SHOULD be committed to source control.\n\n";

  const newSection = [
    `[treasury.${network}]`,
    `account-id = "${entry.accountId}"`,
    `xid = "${entry.xid}"`,
    `handle = "${entry.handle}"`,
    `created-at = "${entry.createdAt}"`,
  ].join("\n");

  let raw = existsSync(treasuryToml) ? readFileSync(treasuryToml, "utf8") : header;
  const sectionRe = new RegExp(`\\[treasury\\.${network}\\][^\\[]*`, "s");
  if (sectionRe.test(raw)) {
    raw = raw.replace(sectionRe, newSection + "\n");
  } else {
    raw = raw.trimEnd() + (raw.length ? "\n\n" : "") + newSection + "\n";
  }
  writeFileSync(treasuryToml, raw, "utf8");
  info(`Updated ${treasuryToml}`);
}

// ── Sui output parsing ────────────────────────────────────────────────────────

type ObjectChange = { type: string; objectId?: string; objectType?: string };

function parseAccountId(json: string): string {
  let parsed: { objectChanges?: ObjectChange[] };
  try {
    parsed = JSON.parse(json);
  } catch {
    die("Failed to parse sui client output as JSON");
  }
  const changes = parsed.objectChanges ?? [];
  const match = changes.find(
    (c) =>
      c.type === "created" && c.objectType?.endsWith("::core::DugongAccount")
  );
  if (!match?.objectId) die("No created DugongAccount found in sui output");
  return match.objectId;
}

// ── usage ─────────────────────────────────────────────────────────────────────

function usage(): never {
  process.stdout.write(`usage: create-treasury.ts [flags]

Flags:
  --network testnet|mainnet    Sui network (default: testnet).
  --package-id <id>            Override DUGONG_PACKAGE_ID source.
  --registry-id <id>           Override DUGONG_REGISTRY_ID source.
  --xid <str>                  Treasury xid (default: TREASURY).
  --handle <str>               Display handle (default: treasury).
  --gas-budget <MIST>          Gas budget (default: 100000000).
  --force                      Overwrite an existing entry for this network.
  --dry-run                    Print the sui command without executing.
  --help                       Show this message.
`);
  process.exit(0);
}

// ── main ──────────────────────────────────────────────────────────────────────

function main(): void {
  const { values } = parseArgs({
    args: process.argv.slice(2),
    allowPositionals: false,
    options: {
      network:      { type: "string",  default: "testnet" },
      "package-id": { type: "string" },
      "registry-id":{ type: "string" },
      xid:          { type: "string",  default: "TREASURY" },
      handle:       { type: "string",  default: "treasury" },
      "gas-budget": { type: "string",  default: "100000000" },
      force:        { type: "boolean", default: false },
      "dry-run":    { type: "boolean", default: false },
      help:         { type: "boolean", default: false },
    },
  });

  if (values.help) usage();

  const network   = values.network!;
  const xid       = values.xid!;
  const handle    = values.handle!;
  const gasBudget = values["gas-budget"]!;
  const dryRun    = !!values["dry-run"];
  const force     = !!values.force;

  if (!["testnet", "mainnet"].includes(network)) {
    die(`Unknown network '${network}'. Use testnet or mainnet.`);
  }

  const existing = readTreasuryToml(network);
  if (existing && !force) {
    die(
      `Treasury already recorded for ${network}: ${existing.accountId}\n` +
      `Pass --force to overwrite, or delete the [treasury.${network}] section.`
    );
  }

  const packageId =
    values["package-id"] ?? readEnvKey(apiEnv, "DUGONG_PACKAGE_ID");
  const registryId =
    values["registry-id"] ?? readEnvKey(apiEnv, "DUGONG_REGISTRY_ID");
  if (!packageId) {
    die(
      "DUGONG_PACKAGE_ID not found in apps/api/.env — pass --package-id explicitly."
    );
  }
  if (!registryId) {
    die(
      "DUGONG_REGISTRY_ID not found in apps/api/.env — pass --registry-id explicitly."
    );
  }

  info(`Network:    ${network}`);
  info(`Package:    ${packageId}`);
  info(`Registry:   ${registryId}`);
  info(`xid:        ${xid}`);
  info(`handle:     ${handle}`);

  const suiArgs = [
    "client", "call",
    "--package", packageId,
    "--module", "account",
    "--function", "init_account_no_signature",
    "--args", registryId, encodeVecU8(xid), encodeVecU8(handle),
    "--gas-budget", gasBudget,
    "--json",
  ];

  const rawJson = run("sui", suiArgs, { dryRun, captureStdout: true });
  if (dryRun) {
    info("Dry-run: skipping Treasury.toml write.");
    return;
  }

  const accountId = parseAccountId(rawJson);
  info(`Treasury account: ${accountId}`);

  writeTreasuryToml(network, {
    accountId,
    xid,
    handle,
    createdAt: new Date().toISOString(),
  });
  patchEnvKey(apiEnv, "MARKET_TREASURY_ACCOUNT_ID", accountId);

  info("Done. apps/api/.env and Treasury.toml are updated.");
  info("Railway is unchanged; run scripts/railway-set-env.ts when you are ready to sync it.");
}

main();
