[package]
name = "dugong"
edition = "2024.beta"

[dependencies]
enclave = { local = "../enclave" }

[addresses]
dugong = "0x0"
enclave = "0x8c4e3fbac387e7427963d4b8b02dec14ea5711fe5cc4b184dae3997f28854507"

[dev-dependencies]

[dev-addresses]
